from typing import List, Dict, Any

ROOMS_DB: List[Dict[str, Any]] = [
    {
        "id": "R001",
        "location": {"city": "Bengaluru", "area": "Koramangala", "pincode": "560095"},
        "rent": 12000,
        "gender_pref": "Any",
        "amenities": ["WiFi", "AC", "Washing Machine"],
        "description": "2BHK near Forum Mall; furnished room with desk.",
        "photo_url": "https://example.com/img1.jpg",
        "posted_by": "user_hash_abc",
        "date_posted": "2025-08-10",
        "is_active": True,
        "expires_at": "2025-09-09",
    },
    {
        "id": "R002",
        "location": {"city": "Bengaluru", "area": "HSR Layout", "pincode": "560102"},
        "rent": 15000,
        "gender_pref": "Female",
        "amenities": ["WiFi", "Geyser", "Balcony"],
        "description": "Sunny room in 3BHK, close to 27th Main.",
        "photo_url": None,
        "posted_by": "user_hash_def",
        "date_posted": "2025-08-08",
        "is_active": True,
        "expires_at": "2025-09-07",
    },
    {
        "id": "R003",
        "location": {"city": "Pune", "area": "Viman Nagar", "pincode": "411014"},
        "rent": 9000,
        "gender_pref": "Male",
        "amenities": ["WiFi"],
        "description": "Affordable PG near Symbiosis, basic amenities.",
        "photo_url": None,
        "posted_by": "user_hash_xyz",
        "date_posted": "2025-08-09",
        "is_active": True,
        "expires_at": "2025-09-08",
    },
    {
        "id": "R004",
        "location": {"city": "Mumbai", "area": "Powai", "pincode": "400076"},
        "rent": 22000,
        "gender_pref": "Any",
        "amenities": ["WiFi", "AC", "Gym"],
        "description": "Powai lake view, gated community with gym.",
        "photo_url": "https://example.com/img_powai.jpg",
        "posted_by": "user_hash_mno",
        "date_posted": "2025-08-05",
        "is_active": True,
        "expires_at": "2025-09-04",
    },
]
